import Head from "next/head";
import Image from "next/image";
import { useQuery, QueryClient, dehydrate } from "@tanstack/react-query";
import shortid from "shortid";
import { getRandomPairPokemon } from "../api/pokemon";
import { useVotePokemon } from "../hooks";
import { checkWhichVote } from "../utils";
import { ImSpinner8 } from "react-icons/im";

export async function getStaticProps() {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery(["pokemon-pair"], getRandomPairPokemon);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}

export default function Home() {
  const {
    data: pokemonPair,
    isLoading,
    isFetching,
  } = useQuery(["pokemon-pair"], getRandomPairPokemon);
  const voteNow = useVotePokemon();
  const vote = (e) => {
    const votedPokemons = checkWhichVote(e, pokemonPair);

    voteNow.mutate(votedPokemons);
  };

  return (
    <>
      <Head>
        <title>Pokemon Vote</title>
        <meta name="pokemon voting" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen bg-gradient-to-r from-vivid-purple to-magneta bg-black grid place-items-center text-white">
        <div className="w-dynamic bg-purple-800  rounded-md overflow-hidden shadow-2xl">
          <h1 className="capitalize p-5 font-bold text-center text-2xl border-x-2 border-t-2">
            Which is the roundest ?
          </h1>
          <div className=" flex gap-8 justify-between flex-col md:flex-row relative  md:h-120 border-x-2 border-y-0 md:border-x-0 md:border-y-2">
            {isFetching ? (
              <div className="absolute inset-0 grid place-items-center">
                <ImSpinner8 className="animate-spin w-14 h-14" />
              </div>
            ) : (
              pokemonPair.map(({ name, img_url }, index) => (
                <figure
                  data-index={index}
                  key={shortid.generate()}
                  className="basis-1/3 flex items-center flex-col cursor-pointer  p-5 hover:bg-white transition-all border-y-2 border-x-0 md:border-x-2 md:border-y-0  group"
                  onClick={vote}
                >
                  <Image
                    src={img_url}
                    width={256}
                    height={256}
                    layout="fixed"
                    alt={`image of ${name} pokemon`}
                  />
                  <hr className="w-full h-px my-4 group-hover:bg-red" />
                  <figcaption className="p-6 text-center font-bold font-mono text-2xl capitalize group-hover:text-black">
                    {name}
                  </figcaption>
                </figure>
              ))
            )}
          </div>
        </div>
      </main>

      <footer className="bg-teal-700 text-white flex items-center justify-center p-5">
        <p>Created By Kerolous Amged</p>
      </footer>
    </>
  );
}
